server {
	listen 80;
	server_name tasken.ru www.tasken.ru dev.tasken.ru;

	location ^~ /.well-known/acme-challenge/ {
		root /var/www/certbot;
		default_type text/plain;
		try_files $uri =404;
	}

	location / {
		return 301 https://$host$request_uri;
	}
}

server {
	listen 443 ssl;
	server_name tasken.ru www.tasken.ru dev.tasken.ru;

	ssl_certificate /etc/letsencrypt/live/tasken.ru/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/tasken.ru/privkey.pem;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers HIGH:!aNULL:!MD5;

	gzip on;
	gzip_vary on;
	gzip_proxied any;
	gzip_comp_level 6;
	gzip_min_length 256;
	gzip_types
	text/plain
	text/css
	text/xml
	text/javascript
	application/javascript
	application/x-javascript
	application/json
	application/xml
	application/rss+xml
	application/atom+xml
	image/svg+xml;

	client_max_body_size 10M;

	location ~ ^/(api|sanctum)(/|$) {
		include fastcgi_params;

		fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
		fastcgi_param SCRIPT_NAME /index.php;
		fastcgi_param DOCUMENT_ROOT /var/www/backend/public;

		fastcgi_param HTTP_PROXY "";
		fastcgi_param HTTP_AUTHORIZATION $http_authorization;

		fastcgi_pass backend:9000;
	}

	location = /up {
		include fastcgi_params;

		fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
		fastcgi_param SCRIPT_NAME /index.php;
		fastcgi_param DOCUMENT_ROOT /var/www/backend/public;

		fastcgi_param HTTP_PROXY "";
		fastcgi_param HTTP_AUTHORIZATION $http_authorization;

		fastcgi_pass backend:9000;
	}

	location / {
		proxy_pass http://frontend:3000;
		proxy_http_version 1.1;

		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;

		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}
